=== tahopen/ccc/doc/schema/com_2012.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="urn:webdetails/com/2012" 
        xmlns:com="urn:webdetails/com/2012" 
        elementFormDefault="qualified">
    
    <!-- 
        List(number) 
        
        Union(string number)
        
        Union(string number List(number))
        
        List(Union(string number))
        
        Union(string number List(Union(string number))
        
        Map(string Object)
        
        Invalid combinations:
          X  List(List(.))
          X  List(Union(List(.) number))
          X  Map(string Map(.))       ??? TODO
          X  Map(string List(Map(.))) ???
          
          X  cycles...
          
        ......................................................
         
                /
          Value | * name  (Lists and Unions may be anonymous)
            ^   \
            |
            |              /
            |....... Union | * types -> Value
            |              \
            |
            |              /
            |....... List  | * elementType -> Item
            |              \
            |
            |              /
            |....... Map   | * keyType   -> Item
            |              | * valueType -> Item // TODO need this restriction?
            |              \
            |
            +....... Item
                       ^
                       |
                       |                     /
                       |.......... ItemUnion | * types -> Item
                       |                     \
                       |
                       |.......... Atom
                       |             ^
                       |             |
                       |             +...... Primitive
                       |
                       |                   /
                       +.......... Complex | * abstract
                                        |  | * baseType -> Complex 
                                        |  \
                                        |                     /
                                        |                     | * name
                                        +........ >> Property | * required
                                                              | * default
                                                              \ 
     -->
     
    <element name="model" type="com:ModelType">
        <!-- Splitting in several files renders these undesirable 
        
        <key name="complexType_unique_name">
            <selector xpath="com:complexType" />
            <field xpath="@space" />
            <field xpath="@name" />
        </key>
        
        <key name="atomType_unique_name">
            <selector xpath="com:atomType" />
            <field xpath="@name" />
        </key>
        
        <key name="funType_unique_name">
            <selector xpath="com:functionType" />
            <field xpath="@name" />
        </key>
        
        <key name="space_unique_name">
            <selector xpath="com:space" />
            <field xpath="@name" />
        </key>
        
         -->
         
        <unique name="model_documentation_format_key">
           <selector xpath="." />
           <field xpath="documentation/@format" />
        </unique>
        
        <unique name="class_documentation_format_key">
           <selector xpath="com:complexType" />
           <field xpath="documentation/@format" />
        </unique>
        
        <unique name="property_documentation_format_key">
           <selector xpath="com:complexType/property" />
           <field xpath="documentation/@format" />
        </unique>
        
        <!-- does not work because of namespace being split in class_key 
        <keyref name="class_keyref" refer="com:class_key">
            <selector xpath="com:complexType" />
            <field xpath="@base" />
        </keyref>
         -->
    </element>
    
    <!-- Elements to be used inside c:documentation elements -->
    <element name="link">
        <complexType>
            <attribute name="to" type="string" use="required" />
        </complexType>
    </element>
    
    <element name="example">
        <complexType mixed="true">
	        <sequence minOccurs="0" maxOccurs="unbounded">
	            <any namespace="##any" processContents="lax" />
	        </sequence>
        </complexType>
    </element>
    
    <element name="deprecated">
        <complexType mixed="true">
            <sequence minOccurs="0" maxOccurs="unbounded">
                <any namespace="##any" processContents="lax" />
            </sequence>
        </complexType>
    </element>
    
    <!-- Model XSD types -->
    
    <complexType name="ModelType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0" maxOccurs="unbounded">
                <element name="space" type="com:SpaceType" />
	            <element name="complexType" type="com:ComplexTypeType">
	                <key name="complex_unique_prop_name">
                        <selector xpath="com:property" />
                        <field xpath="@name" />
                    </key>
	            </element>
	            <element name="atomType" type="com:AtomTypeType">
	                <key name="atom_unique_name">
			            <selector xpath="com:atom" />
			            <field xpath="@name" />
			        </key>
			        <key name="atom_unique_value">
			            <selector xpath="com:atom" />
			            <field xpath="@value" />
			        </key>
	            </element>
	            <element name="functionType" type="com:FunctionTypeType" />
	            <element name="facetType" type="com:FacetTypeType" />
	            <element name="include">
			        <complexType>
			            <attribute name="the" type="string" use="required" /> 
			        </complexType>
			    </element>
	       </choice>
       </sequence>
    </complexType>
    
    <complexType name="SpaceType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
       </sequence>
       <attribute name="name" type="com:IdType" use="required" />
    </complexType>
    
    <complexType name="ComplexTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="property" type="com:PropertyType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
        <attribute name="facets" type="com:IdTypeList" />
        <attribute name="abstract" type="boolean" default="false" />
        <attribute name="use" type="com:ComplexUseType" default="literal" />
    </complexType>
    
    <complexType name="FacetTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="property" type="com:PropertyType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <!-- 
        <attribute name="base" type="com:IdType" />
        <attribute name="abstract" type="boolean" default="false" />
         -->
    </complexType>
    
    <complexType name="PropertyType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="type" type="com:ValueTypeType" default="string" />
        <attribute name="required" type="boolean" default="false" />
        <attribute name="default" type="anySimpleType" />
        <attribute name="fixed" type="anySimpleType" />
        <attribute name="category" type="string" />
        <attribute name="expandUse" type="com:PropertyExpandUseType" default="required" />
        <attribute name="excludeIn" type="NMTOKENS" /> 
        <attribute name="level" type="com:PropertyLevelType" default="advanced" />
    </complexType>
    
    <complexType name="AtomTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="atom" type="com:AtomType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
    </complexType>
    
    <complexType name="AtomType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name"  type="com:IdType" use="required" />
        <attribute name="value" type="anySimpleType" use="required" />
    </complexType>
    
    <complexType name="FunctionTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="argument" type="com:ArgumentType" minOccurs="0" maxOccurs="unbounded" />
            <element name="returns"  type="com:ReturnType" minOccurs="0" maxOccurs="1" />
        </sequence>
        
        <attribute name="name"  type="com:IdType" use="required" />
        <attribute name="space" type="string" />
    </complexType>
    
    <complexType name="ArgumentType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="type" type="com:ValueTypeType" use="optional" default="undefined" />
        <attribute name="required" type="boolean" default="false" />
        <attribute name="default" type="anySimpleType" use="optional" />
    </complexType>
    
    <complexType name="ReturnType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="type" type="com:ValueTypeType" use="optional" default="undefined" />
    </complexType>
    
    <complexType name="DocumentationType" mixed="true">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <any namespace="##any" processContents="lax" />
        </sequence>
        
        <attribute name="format" type="com:DocumentationFormatType" use="optional" />
    </complexType>
    
    <simpleType name="ValueTypeType">
        <union memberTypes="com:PrimitiveSimpleTypeType string" />
    </simpleType>
    
    <simpleType name="PrimitiveSimpleTypeType">
        <restriction base="string">
            <enumeration value="undefined" />
            <enumeration value="literal" />
            <enumeration value="string" />
            <enumeration value="number" />
            <enumeration value="boolean" />
            <enumeration value="object" />
            <enumeration value="function" />
            <enumeration value="date" />
            <enumeration value="percentage" />
        </restriction>
    </simpleType>
    
    <simpleType name="ComplexUseType">
        <restriction base="string">
            <enumeration value="literal" />
            <enumeration value="expanded" />
            <enumeration value="any" />
        </restriction>
    </simpleType>
    
    <simpleType name="PropertyExpandUseType">
        <restriction base="string">
            <enumeration value="optional" />
            <enumeration value="required" />
        </restriction>
    </simpleType>
    
    <!-- A measure of difficulty or frequency of use of a property -->
    <simpleType name="PropertyLevelType">
        <restriction base="string">
            <enumeration value="basic" />
            <enumeration value="intermediate" />
            <enumeration value="advanced" />
        </restriction>
    </simpleType>
    
    <simpleType name="IdType">
        <restriction base="NMTOKEN" />
    </simpleType>
    
    <simpleType name="IdTypeList">
        <list itemType="com:IdType" />
    </simpleType>
    
    <simpleType name="DocumentationFormatType">
        <restriction base="string">
           <enumeration value="markdown" />
           <enumeration value="jsdoc" />
           <enumeration value="com" />
        </restriction>
    </simpleType>
</schema>

=== tahopen/ccc/doc/model/facets/plotLinesAndDots.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:facetType name="LinesAndDotsPlotFacet" space="pvc.options.plots">
        <c:documentation>
            The options documentation class of the lines and dots plot facet.
        </c:documentation>
        
        <c:property name="dotsVisible" type="boolean" default="false" category="Style">
            <c:documentation>
                Indicates if the visual elements show dots/markers
                in each point's position.
            </c:documentation>
        </c:property>
        
        <c:property name="linesVisible" type="boolean" default="false" category="Style">
            <c:documentation>
                Indicates if the visual elements are connected
                with lines.
            </c:documentation>
        </c:property>
        
        <c:property name="showDots" type="boolean" category="Style">
            <c:documentation>
                <c:deprecated>Use <c:link to="#dotsVisible" /> instead.</c:deprecated>
                Indicates if the visual elements show dots/markers
                in each point's position.
            </c:documentation>
        </c:property>
        
        <c:property name="showLines" type="boolean" category="Style">
            <c:documentation>
                <c:deprecated>Use <c:link to="#linesVisible" /> instead.</c:deprecated>
                Indicates if the visual elements are connected
                with lines.
            </c:documentation>
        </c:property>
    </c:facetType>
    
</c:model>

=== tahopen/ccc/doc/model/varia/atoms/panelPosition.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">

    <c:atomType name="PanelPosition" space="pvc.options.varia" base="string">
        <c:documentation>
            The sides of a parent panel to 
            which a child panel may be docked to.
        </c:documentation>
        
        <c:atom name="Left" value="'left'">
            <c:documentation>
                The left side of the child panel 
                is placed at the same position as the
                left side of the parent panel. 
            </c:documentation>
        </c:atom>
        
        <c:atom name="Right" value="'right'">
            <c:documentation>
                The right side of the child panel 
                is placed at the same position as the
                right side of the parent panel. 
            </c:documentation>
        </c:atom>
        
        <c:atom name="Top" value="'top'">
            <c:documentation>
                The top side of the child panel 
                is placed at the same position as the
                top side of the parent panel. 
            </c:documentation>
        </c:atom>
        
        <c:atom name="Bottom" value="'bottom'">
            <c:documentation>
                The bottom side of the child panel 
                is placed at the same position as the
                bottom side of the parent panel. 
            </c:documentation>
        </c:atom>
    </c:atomType>
</c:model>

=== tahopen/ccc/doc/model/marks/rule.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="RuleExtensionPoint" 
                   space="pvc.options.marks" 
                   base="pvc.options.marks.MarkExtensionPoint"
                   facets="pvc.options.marks.StrokeBasicFacet">
         <c:documentation>
            The class of protovis Rule extension points.
            
            See the associated protovis documentation at
            <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Rule.html" />.
        </c:documentation>
        
        <c:property name="width" type="number">
            <c:documentation>
                The width of the rule, when it is horizontal.
            </c:documentation>
        </c:property>
        
        <c:property name="height" type="number">
            <c:documentation>
                The height of the rule, when it is vertical.
            </c:documentation>
        </c:property>
        
    </c:complexType>
    
</c:model>

=== tahopen/ccc/doc/model/facets/_facets.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:include the="facets/chartMulti.xml" />
    <c:include the="facets/chartPlot2.xml" />
    <c:include the="facets/chartTrend.xml" />
    <c:include the="facets/extMulti.xml" />
    <c:include the="facets/plotLinesAndDots.xml" />
    <c:include the="facets/plotMain.xml" />
    <c:include the="facets/plotValuesOverflow.xml" />
</c:model>

=== tahopen/ccc/doc/model/varia/atoms/panelAlignment.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">

    <c:atomType name="PanelAlignmentSource" space="pvc.options.varia" base="string">
        <c:documentation>
            The sides of a child panel, the source, 
            that can be aligned with 
            a target side of a parent panel.
            
            The alignment side must be 
            orthogonal to the side of 
            the <c:link to="pvc.options.varia.PanelPosition" />.
            
            By combining the alignment source
            with the <c:link to="pvc.options.varia.PanelAlignmentTarget"/>,
            different alignment combinations can be achieved.
            
            The alignment target side must be 
            parallel to the side of source alignment.
        </c:documentation>
        
        <c:atom name="Left" value="'left'">
            <c:documentation>
                The left side of the child panel 
                is placed at the same position as the
                target side of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Center" value="'center'">
            <c:documentation>
                The horizontal center position of the child panel 
                is placed at the same position as the
                target side of the parent panel. 
            </c:documentation>
        </c:atom>
        
        <c:atom name="Right" value="'right'">
            <c:documentation>
                The right side of the child panel 
                is placed at the same position as the
                target side of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Top" value="'top'">
            <c:documentation>
                The top side of the child panel 
                is placed at the same position as the
                target side of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Middle" value="'middle'">
            <c:documentation>
                The vertical center position of the child panel 
                is placed at the same position as the
                target side of the parent panel. 
            </c:documentation>
        </c:atom>
        
        <c:atom name="Bottom" value="'bottom'">
            <c:documentation>
                The bottom side of the child panel 
                is placed at the same position as the
                target side of the parent panel. 
            </c:documentation>
        </c:atom>
    </c:atomType>
    
    <c:atomType name="PanelAlignmentTarget" space="pvc.options.varia" base="string">
        <c:documentation>
            The sides of a parent panel, the target, 
            with which the alignment side of a source child panel 
            can be aligned to.
            
            The alignment target side must be 
            parallel to the side of source alignment.
            
            Wherever an alignment target argument is found,
            a value of type <tt>number</tt>,
            a numeric <tt>string</tt> or 
            a numeric percentage <tt>string</tt>, 
            may also be specified.
            
            In this case, 
            these specify the position of alignment, 
            from the left or top sides,
            whichever is parallel to the alignment source side.
            
            For example, if the source alignment side is <tt>'right'</tt>
            and the target alignment specifies <tt>'10%'</tt>,
            then the right side of the child panel would be
            placed at a position of 
            10% of the parent panel's client width
            from the parent's left side.
        </c:documentation>
        
        <c:atom name="Left" value="'left'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                left side of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Center" value="'center'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                horizontal center position of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Right" value="'right'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                right side of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Top" value="'top'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                top side of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Middle" value="'middle'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                vertical center position of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="PageMiddle" value="'page-middle'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                vertical center position of the 
                <i>page</i> height of the parent panel.
                
                The page height differs from the chart height
                in that the 
                page height is by definition 
                the value initially specified in 
                <c:link to="pvc.options.charts.BasicChart#height" />,
                and the chart height 
                can grow if layout so requires it,
                like it does in <i>small multiples</i> charts.
                
                The page middle alignment allows, 
                for example, 
                placing the legend panel in 
                the middle of the screen height,
                even though the height of the chart
                may have become much larger.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Bottom" value="'bottom'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                bottom side of the parent panel.
            </c:documentation>
        </c:atom>
    </c:atomType>
    
</c:model>

=== tahopen/ccc/doc/model/varia/atoms/multiChartOverflow.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:atomType name="MultiChartOverflow" space="pvc.options.varia" base="string">
        <c:documentation>
            The possible strategies for when the number of small charts
            overflows the initial chart dimensions.
        </c:documentation>
        
        <c:atom name="Grow" value="'grow'">
            <c:documentation>
                The chart grows in size as needed to fit all of the small-charts.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Fit" value="'fit'">
            <c:documentation>
                The small-charts are sized so that they all fit the initial chart size.
            </c:documentation>
        </c:atom>

        <c:atom name="Clip" value="'clip'">
            <c:documentation>
                Only the first small-charts that entirely fit 
                in the initial chart size are actually shown.
                
                An overflow indicator is shown by default.
            </c:documentation>
        </c:atom>
    </c:atomType>
</c:model>
