=== tahopen/ccc/doc/schema/com_2012.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="urn:webdetails/com/2012" 
        xmlns:com="urn:webdetails/com/2012" 
        elementFormDefault="qualified">
    
    <!-- 
        List(number) 
        
        Union(string number)
        
        Union(string number List(number))
        
        List(Union(string number))
        
        Union(string number List(Union(string number))
        
        Map(string Object)
        
        Invalid combinations:
          X  List(List(.))
          X  List(Union(List(.) number))
          X  Map(string Map(.))       ??? TODO
          X  Map(string List(Map(.))) ???
          
          X  cycles...
          
        ......................................................
         
                /
          Value | * name  (Lists and Unions may be anonymous)
            ^   \
            |
            |              /
            |....... Union | * types -> Value
            |              \
            |
            |              /
            |....... List  | * elementType -> Item
            |              \
            |
            |              /
            |....... Map   | * keyType   -> Item
            |              | * valueType -> Item // TODO need this restriction?
            |              \
            |
            +....... Item
                       ^
                       |
                       |                     /
                       |.......... ItemUnion | * types -> Item
                       |                     \
                       |
                       |.......... Atom
                       |             ^
                       |             |
                       |             +...... Primitive
                       |
                       |                   /
                       +.......... Complex | * abstract
                                        |  | * baseType -> Complex 
                                        |  \
                                        |                     /
                                        |                     | * name
                                        +........ >> Property | * required
                                                              | * default
                                                              \ 
     -->
     
    <element name="model" type="com:ModelType">
        <!-- Splitting in several files renders these undesirable 
        
        <key name="complexType_unique_name">
            <selector xpath="com:complexType" />
            <field xpath="@space" />
            <field xpath="@name" />
        </key>
        
        <key name="atomType_unique_name">
            <selector xpath="com:atomType" />
            <field xpath="@name" />
        </key>
        
        <key name="funType_unique_name">
            <selector xpath="com:functionType" />
            <field xpath="@name" />
        </key>
        
        <key name="space_unique_name">
            <selector xpath="com:space" />
            <field xpath="@name" />
        </key>
        
         -->
         
        <unique name="model_documentation_format_key">
           <selector xpath="." />
           <field xpath="documentation/@format" />
        </unique>
        
        <unique name="class_documentation_format_key">
           <selector xpath="com:complexType" />
           <field xpath="documentation/@format" />
        </unique>
        
        <unique name="property_documentation_format_key">
           <selector xpath="com:complexType/property" />
           <field xpath="documentation/@format" />
        </unique>
        
        <!-- does not work because of namespace being split in class_key 
        <keyref name="class_keyref" refer="com:class_key">
            <selector xpath="com:complexType" />
            <field xpath="@base" />
        </keyref>
         -->
    </element>
    
    <!-- Elements to be used inside c:documentation elements -->
    <element name="link">
        <complexType>
            <attribute name="to" type="string" use="required" />
        </complexType>
    </element>
    
    <element name="example">
        <complexType mixed="true">
	        <sequence minOccurs="0" maxOccurs="unbounded">
	            <any namespace="##any" processContents="lax" />
	        </sequence>
        </complexType>
    </element>
    
    <element name="deprecated">
        <complexType mixed="true">
            <sequence minOccurs="0" maxOccurs="unbounded">
                <any namespace="##any" processContents="lax" />
            </sequence>
        </complexType>
    </element>
    
    <!-- Model XSD types -->
    
    <complexType name="ModelType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0" maxOccurs="unbounded">
                <element name="space" type="com:SpaceType" />
	            <element name="complexType" type="com:ComplexTypeType">
	                <key name="complex_unique_prop_name">
                        <selector xpath="com:property" />
                        <field xpath="@name" />
                    </key>
	            </element>
	            <element name="atomType" type="com:AtomTypeType">
	                <key name="atom_unique_name">
			            <selector xpath="com:atom" />
			            <field xpath="@name" />
			        </key>
			        <key name="atom_unique_value">
			            <selector xpath="com:atom" />
			            <field xpath="@value" />
			        </key>
	            </element>
	            <element name="functionType" type="com:FunctionTypeType" />
	            <element name="facetType" type="com:FacetTypeType" />
	            <element name="include">
			        <complexType>
			            <attribute name="the" type="string" use="required" /> 
			        </complexType>
			    </element>
	       </choice>
       </sequence>
    </complexType>
    
    <complexType name="SpaceType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
       </sequence>
       <attribute name="name" type="com:IdType" use="required" />
    </complexType>
    
    <complexType name="ComplexTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="property" type="com:PropertyType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
        <attribute name="facets" type="com:IdTypeList" />
        <attribute name="abstract" type="boolean" default="false" />
        <attribute name="use" type="com:ComplexUseType" default="literal" />
    </complexType>
    
    <complexType name="FacetTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="property" type="com:PropertyType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <!-- 
        <attribute name="base" type="com:IdType" />
        <attribute name="abstract" type="boolean" default="false" />
         -->
    </complexType>
    
    <complexType name="PropertyType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="type" type="com:ValueTypeType" default="string" />
        <attribute name="required" type="boolean" default="false" />
        <attribute name="default" type="anySimpleType" />
        <attribute name="fixed" type="anySimpleType" />
        <attribute name="category" type="string" />
        <attribute name="expandUse" type="com:PropertyExpandUseType" default="required" />
        <attribute name="excludeIn" type="NMTOKENS" /> 
        <attribute name="level" type="com:PropertyLevelType" default="advanced" />
    </complexType>
    
    <complexType name="AtomTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="atom" type="com:AtomType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
    </complexType>
    
    <complexType name="AtomType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name"  type="com:IdType" use="required" />
        <attribute name="value" type="anySimpleType" use="required" />
    </complexType>
    
    <complexType name="FunctionTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="argument" type="com:ArgumentType" minOccurs="0" maxOccurs="unbounded" />
            <element name="returns"  type="com:ReturnType" minOccurs="0" maxOccurs="1" />
        </sequence>
        
        <attribute name="name"  type="com:IdType" use="required" />
        <attribute name="space" type="string" />
    </complexType>
    
    <complexType name="ArgumentType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="type" type="com:ValueTypeType" use="optional" default="undefined" />
        <attribute name="required" type="boolean" default="false" />
        <attribute name="default" type="anySimpleType" use="optional" />
    </complexType>
    
    <complexType name="ReturnType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="type" type="com:ValueTypeType" use="optional" default="undefined" />
    </complexType>
    
    <complexType name="DocumentationType" mixed="true">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <any namespace="##any" processContents="lax" />
        </sequence>
        
        <attribute name="format" type="com:DocumentationFormatType" use="optional" />
    </complexType>
    
    <simpleType name="ValueTypeType">
        <union memberTypes="com:PrimitiveSimpleTypeType string" />
    </simpleType>
    
    <simpleType name="PrimitiveSimpleTypeType">
        <restriction base="string">
            <enumeration value="undefined" />
            <enumeration value="literal" />
            <enumeration value="string" />
            <enumeration value="number" />
            <enumeration value="boolean" />
            <enumeration value="object" />
            <enumeration value="function" />
            <enumeration value="date" />
            <enumeration value="percentage" />
        </restriction>
    </simpleType>
    
    <simpleType name="ComplexUseType">
        <restriction base="string">
            <enumeration value="literal" />
            <enumeration value="expanded" />
            <enumeration value="any" />
        </restriction>
    </simpleType>
    
    <simpleType name="PropertyExpandUseType">
        <restriction base="string">
            <enumeration value="optional" />
            <enumeration value="required" />
        </restriction>
    </simpleType>
    
    <!-- A measure of difficulty or frequency of use of a property -->
    <simpleType name="PropertyLevelType">
        <restriction base="string">
            <enumeration value="basic" />
            <enumeration value="intermediate" />
            <enumeration value="advanced" />
        </restriction>
    </simpleType>
    
    <simpleType name="IdType">
        <restriction base="NMTOKEN" />
    </simpleType>
    
    <simpleType name="IdTypeList">
        <list itemType="com:IdType" />
    </simpleType>
    
    <simpleType name="DocumentationFormatType">
        <restriction base="string">
           <enumeration value="markdown" />
           <enumeration value="jsdoc" />
           <enumeration value="com" />
        </restriction>
    </simpleType>
</schema>

=== tahopen/ccc/doc/model/varia/atoms/stroke.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:atomType name="StrokeLineJoin" space="pvc.options.varia" base="string">
        <c:documentation>
            The possible ways to join the segments of a line.
            
            See <c:link to="http://www.w3.org/TR/SVG/painting.html#StrokeProperties" />
            for more information on stroke properties.
        </c:documentation>
        
        <c:atom name="Miter" value="'miter'">
            <c:documentation>
                Join segments with sharp angle corners. 
            </c:documentation>
        </c:atom>
        <c:atom name="Round" value="'round'">
            <c:documentation>
                Join segments with rounded corners.
            </c:documentation>
        </c:atom>
        <c:atom name="Bevel" value="'bevel'">
            <c:documentation>
                Join segments with cut-off corners.
            </c:documentation>
        </c:atom>
    </c:atomType>
    
    <c:atomType name="StrokeLineCap" space="pvc.options.varia" base="string">
        <c:documentation>
            The possible ways to draw the ends of a line or line pattern.
            
            See <c:link to="http://www.w3.org/TR/SVG/painting.html#StrokeProperties" />
            for more information on stroke properties.
        </c:documentation>
        
        <c:atom name="Butt" value="'butt'">
            <c:documentation>
                The end is straight, at the end position. 
            </c:documentation>
        </c:atom>
        <c:atom name="Round" value="'round'">
            <c:documentation>
                The end is a semi-circle,
                whose radius is half the line width
                and whose center is at the end position.
            </c:documentation>
        </c:atom>
        <c:atom name="Square" value="'square'">
            <c:documentation>
                The end is a square,
                whith a side length equal to the line width
                and whose center is at the end position.
            </c:documentation>
        </c:atom>
    </c:atomType>
    
    <c:atomType name="StrokeDasharray" space="pvc.options.varia" base="string">
        <c:documentation>
            The possible stroke patterns.
            
            The actual length of stroke patterns' dashes and spaces is 
            proportional to the line width. 
            
            The pattern dashes are sensitive to 
            the line cap property. 
            The use of <c:link to="pvc.options.varia.StrokeLineCap#Round" />
            generates circle-ended dashes.
            The line caps <c:link to="pvc.options.varia.StrokeLineCap#Butt" />
            and <c:link to="pvc.options.varia.StrokeLineCap#Square" />
            yield the same result: 
            square-ended dashes, of equal length.
            
            See <c:link to="http://www.w3.org/TR/SVG/painting.html#StrokeProperties" />
            for more information on stroke properties.
        </c:documentation>
        
        <c:atom name="ShortDash" value="'shortdash'">
            <c:documentation>
                 A pattern.
                 Can also be specified as <tt>"."</tt>
            </c:documentation>
        </c:atom>
        <c:atom name="ShortDashDot" value="'shortdashdot'">
            <c:documentation>
                 A pattern.
                 Can also be specified as <tt>"-."</tt>
            </c:documentation>
        </c:atom>
        <c:atom name="ShortDashDotDot" value="'shortdashdotdot'">
            <c:documentation>
                 A pattern.
                 Can also be specified as <tt>"-.."</tt>
            </c:documentation>
        </c:atom>
        <c:atom name="Dot" value="'dot'">
            <c:documentation>
                A pattern.
                Can also be specified as <tt>". "</tt>
            </c:documentation>
        </c:atom>
        <c:atom name="Dash" value="'dash'">
            <c:documentation>
                A pattern.
                Can also be specified as <tt>"- "</tt>
            </c:documentation>
        </c:atom>
        <c:atom name="LongDash" value="'longdash'">
            <c:documentation>
                 A pattern.
                 Can also be specified as <tt>"--"</tt>
            </c:documentation>
        </c:atom>
        <c:atom name="DashDot" value="'dashdot'">
            <c:documentation>
                 A pattern.
                 Can also be specified as <tt>"- ."</tt>
            </c:documentation>
        </c:atom>
        <c:atom name="LongDashDot" value="'longdashdot'">
            <c:documentation>
                 A pattern.
                 Can also be specified as <tt>"--."</tt>
            </c:documentation>
        </c:atom>
        <c:atom name="LongDashDotDot" value="'longdashdotdot'">
            <c:documentation>
                 A pattern.
                 Can also be specified as <tt>"--.."</tt>
            </c:documentation>
        </c:atom>
    </c:atomType>
</c:model>

=== tahopen/ccc/doc/model/panels/common.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="Panel" 
                   space="pvc.options.panels"
                   abstract="true">
        <c:documentation>
            The common options documentation class of the CCC panels.
        </c:documentation>
        
        <c:property name="size" type="number string pvc.options.varia.Size" category="Layout">
            <c:documentation>
                The fixed size of the panel, in pixel units or as a percentage.
                
                See <c:link to="pvc.options.varia.Size" /> for information about 
                the different supported data types.
            </c:documentation>
        </c:property>
        
        <c:property name="sizeMax" type="number string pvc.options.varia.Size" category="Layout">
            <c:documentation>
                The maximum size of the panel, in pixel units or as a percentage.
                
                See <c:link to="pvc.options.varia.Size" /> for information about 
                the different supported data types.
            </c:documentation>
        </c:property>
    </c:complexType>
    
</c:model>

=== tahopen/ccc/doc/model/format/numberFormatStyle.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">

    <c:complexType name="NumberFormatStyle" space="pvc.options.format" use="literal">
        <c:documentation>
            The options documentation of the number format style class.

            The options in this class are mostly useful for
            customizing locale sensitive styles of number formatting.

            See <c:link to="pvc.options.format.FormatProvider" /> for
            more information on inheritance of formatting configurations.
        </c:documentation>

        <c:property name="decimal" type="string" default="'.'" required="true">
            <c:documentation>
                The character to use in place of the "." mask character.
                The decimal point separates the integer and fraction parts of the number.
            </c:documentation>
        </c:property>

        <c:property name="group" type="string" default="','">
            <c:documentation>
                The character to use in place of the "," mask character.
                The group separator groups integer digits according to the sizes in <tt>groupSizes</tt>.
                Grouping can be disabled, independently of the mask, by specifying "".
            </c:documentation>
        </c:property>

        <c:property name="groupSizes" type="list(number)" default="[3]" required="true">
            <c:documentation>
                The array of group sizes.
                The last group is repeated indefinitely.
                The array must contain at least one element.
            </c:documentation>
        </c:property>

        <c:property name="negativeSign" type="string" default="'-'" required="true">
            <c:documentation>
                The negative sign character.
                The negative sign is used to indicate a negative number
                when a mask does not have a negative values section.
                The negative sign is placed leftmost in the resulting string.
                The negative sign is also used for showing a negative exponent,
                in scientific notation.
            </c:documentation>
        </c:property>

        <c:property name="currency" type="string" default="'$'" required="true">
            <c:documentation>
                Gets or sets the currency symbol to use in place of the "¤" mask character.

                The <b>currency sign</b> ¤ is a character used to denote an unspecified currency.
                Its unicode is U+00A4 and
                its HTML entities are &amp;amp;#164; and &amp;amp;curren;

                See <c:link to="http://en.wikipedia.org/wiki/Currency_sign_(typography)" /> for
                more information on the currency sign character.
            </c:documentation>
        </c:property>

        <c:property name="integerPad" type="string" default="'0'" required="true">
            <c:documentation>
                The character to use in place of a "0" mask character in the integer part.
            </c:documentation>
        </c:property>

        <c:property name="fractionPad" type="string" default="'0'" required="true">
            <c:documentation>
                The character to use in place of a "0" mask character in the fractional part.
            </c:documentation>
        </c:property>

        <c:property name="abbreviations" type="list(string)" default="['k','m','b','t']" required="true">
            <c:documentation>
                The array of abbreviations.
                There is no maximum number of units abbreviations.
                The first element of the array represents the Thousands unit,
                the second Millions, the third Billions...
            </c:documentation>
        </c:property>
    </c:complexType>

</c:model>

=== tahopen/ccc/doc/model/varia/functions/colorTransform.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:functionType name="ColorTransform" space="pvc.options.varia">
        <c:documentation>
            A function that applies an effect to 
            an input color and returns the resulting color.
        </c:documentation>
        <c:argument name="this" type="null" required="true">
            <c:documentation>
                The global JavaScript object.
            </c:documentation>
        </c:argument>
        <c:argument name="color" type="pv.Color" required="true">
            <c:documentation>
                The color to transform.
            </c:documentation>
        </c:argument>
        <c:returns type="pv.Color">
            <c:documentation>
                The transformed color.
            </c:documentation>
        </c:returns>
    </c:functionType>
    
</c:model>

=== tahopen/ccc/doc/model/marks/label.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="LabelExtensionPoint" 
                   space="pvc.options.marks"
                   base="pvc.options.marks.MarkExtensionPoint">
         <c:documentation>
            The class of protovis Label extension points.
            
            See the associated protovis documentation at
            <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Label.html" />.
        </c:documentation>
        
        <c:property name="font" type="string">
            <c:documentation>
                The font used by the label.
                
                See the supported font format in 
                <c:link to="http://www.w3.org/TR/CSS2/fonts.html#font-shorthand" />
            </c:documentation>
        </c:property>
        
        <c:property name="text" type="string">
            <c:documentation>
                The text to show in the label.
            </c:documentation>
        </c:property>
        
        <c:property name="textStyle" type="pvc.options.varia.ColorString">
            <c:documentation>
                The text color.
                
                Note that gradients are not supported in the text style.
            </c:documentation>
        </c:property>
        
        <c:property name="textAngle" type="number" default="0">
            <c:documentation>
                The angle of the text, in <i>radian</i> units.
                
                The text angle is 0 at horizontal direction 
                and grows clock-wise. 
            </c:documentation>
        </c:property>
        
        <c:property name="textAlign" type="pvc.options.varia.TextAlignment">
            <c:documentation>
                The horizontal text alignment.
            </c:documentation>
        </c:property>
        
        <c:property name="textMargin" type="number">
            <c:documentation>
                The vertical and horizontal distance that separates the label's <i>anchor point</i>
                from its associated visual element's anchor point 
                (usually configurable by the <c:link to="pvc.options.plots.Plot#valuesAnchor" /> option).
                
                The margin is only applied vertically if 
                <c:link to="#textBaseline" /> is not <c:link to="pvc.options.varia.TextBaseline#Middle" />.
                Likewise, the margin is only applied horizontally if 
                <c:link to="#textAlign" /> is not <c:link to="pvc.options.varia.TextAlignment#Center" />.
                Together, the previous two properties define the label's anchor point.
            </c:documentation>
        </c:property>

        <c:property name="textBaseline" type="pvc.options.varia.TextBaseline">
            <c:documentation>
                The vertical text alignment.
            </c:documentation>
        </c:property>
        
        <c:property name="textDecoration" type="string">
            <c:documentation>
                A CSS3 text decoration.
                
                See the syntax of this string at:
                <c:link to="http://www.w3.org/TR/2012/WD-css-text-decor-3-20121113/#text-decoration" />.
            </c:documentation>
        </c:property>
        
        <c:property name="textShadow" type="string">
            <c:documentation>
                A CSS3 text shadow.
                
                See the syntax of this string at:
                <c:link to="http://www.w3.org/TR/2012/WD-css-text-decor-3-20121113/#text-shadow-property" />.
            </c:documentation>
        </c:property>
    </c:complexType>
</c:model>
