=== tahopen/ccc/doc/schema/com_2012.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="urn:webdetails/com/2012" 
        xmlns:com="urn:webdetails/com/2012" 
        elementFormDefault="qualified">
    
    <!-- 
        List(number) 
        
        Union(string number)
        
        Union(string number List(number))
        
        List(Union(string number))
        
        Union(string number List(Union(string number))
        
        Map(string Object)
        
        Invalid combinations:
          X  List(List(.))
          X  List(Union(List(.) number))
          X  Map(string Map(.))       ??? TODO
          X  Map(string List(Map(.))) ???
          
          X  cycles...
          
        ......................................................
         
                /
          Value | * name  (Lists and Unions may be anonymous)
            ^   \
            |
            |              /
            |....... Union | * types -> Value
            |              \
            |
            |              /
            |....... List  | * elementType -> Item
            |              \
            |
            |              /
            |....... Map   | * keyType   -> Item
            |              | * valueType -> Item // TODO need this restriction?
            |              \
            |
            +....... Item
                       ^
                       |
                       |                     /
                       |.......... ItemUnion | * types -> Item
                       |                     \
                       |
                       |.......... Atom
                       |             ^
                       |             |
                       |             +...... Primitive
                       |
                       |                   /
                       +.......... Complex | * abstract
                                        |  | * baseType -> Complex 
                                        |  \
                                        |                     /
                                        |                     | * name
                                        +........ >> Property | * required
                                                              | * default
                                                              \ 
     -->
     
    <element name="model" type="com:ModelType">
        <!-- Splitting in several files renders these undesirable 
        
        <key name="complexType_unique_name">
            <selector xpath="com:complexType" />
            <field xpath="@space" />
            <field xpath="@name" />
        </key>
        
        <key name="atomType_unique_name">
            <selector xpath="com:atomType" />
            <field xpath="@name" />
        </key>
        
        <key name="funType_unique_name">
            <selector xpath="com:functionType" />
            <field xpath="@name" />
        </key>
        
        <key name="space_unique_name">
            <selector xpath="com:space" />
            <field xpath="@name" />
        </key>
        
         -->
         
        <unique name="model_documentation_format_key">
           <selector xpath="." />
           <field xpath="documentation/@format" />
        </unique>
        
        <unique name="class_documentation_format_key">
           <selector xpath="com:complexType" />
           <field xpath="documentation/@format" />
        </unique>
        
        <unique name="property_documentation_format_key">
           <selector xpath="com:complexType/property" />
           <field xpath="documentation/@format" />
        </unique>
        
        <!-- does not work because of namespace being split in class_key 
        <keyref name="class_keyref" refer="com:class_key">
            <selector xpath="com:complexType" />
            <field xpath="@base" />
        </keyref>
         -->
    </element>
    
    <!-- Elements to be used inside c:documentation elements -->
    <element name="link">
        <complexType>
            <attribute name="to" type="string" use="required" />
        </complexType>
    </element>
    
    <element name="example">
        <complexType mixed="true">
	        <sequence minOccurs="0" maxOccurs="unbounded">
	            <any namespace="##any" processContents="lax" />
	        </sequence>
        </complexType>
    </element>
    
    <element name="deprecated">
        <complexType mixed="true">
            <sequence minOccurs="0" maxOccurs="unbounded">
                <any namespace="##any" processContents="lax" />
            </sequence>
        </complexType>
    </element>
    
    <!-- Model XSD types -->
    
    <complexType name="ModelType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0" maxOccurs="unbounded">
                <element name="space" type="com:SpaceType" />
	            <element name="complexType" type="com:ComplexTypeType">
	                <key name="complex_unique_prop_name">
                        <selector xpath="com:property" />
                        <field xpath="@name" />
                    </key>
	            </element>
	            <element name="atomType" type="com:AtomTypeType">
	                <key name="atom_unique_name">
			            <selector xpath="com:atom" />
			            <field xpath="@name" />
			        </key>
			        <key name="atom_unique_value">
			            <selector xpath="com:atom" />
			            <field xpath="@value" />
			        </key>
	            </element>
	            <element name="functionType" type="com:FunctionTypeType" />
	            <element name="facetType" type="com:FacetTypeType" />
	            <element name="include">
			        <complexType>
			            <attribute name="the" type="string" use="required" /> 
			        </complexType>
			    </element>
	       </choice>
       </sequence>
    </complexType>
    
    <complexType name="SpaceType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
       </sequence>
       <attribute name="name" type="com:IdType" use="required" />
    </complexType>
    
    <complexType name="ComplexTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="property" type="com:PropertyType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
        <attribute name="facets" type="com:IdTypeList" />
        <attribute name="abstract" type="boolean" default="false" />
        <attribute name="use" type="com:ComplexUseType" default="literal" />
    </complexType>
    
    <complexType name="FacetTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="property" type="com:PropertyType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <!-- 
        <attribute name="base" type="com:IdType" />
        <attribute name="abstract" type="boolean" default="false" />
         -->
    </complexType>
    
    <complexType name="PropertyType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="type" type="com:ValueTypeType" default="string" />
        <attribute name="required" type="boolean" default="false" />
        <attribute name="default" type="anySimpleType" />
        <attribute name="fixed" type="anySimpleType" />
        <attribute name="category" type="string" />
        <attribute name="expandUse" type="com:PropertyExpandUseType" default="required" />
        <attribute name="excludeIn" type="NMTOKENS" /> 
        <attribute name="level" type="com:PropertyLevelType" default="advanced" />
    </complexType>
    
    <complexType name="AtomTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="atom" type="com:AtomType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
    </complexType>
    
    <complexType name="AtomType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name"  type="com:IdType" use="required" />
        <attribute name="value" type="anySimpleType" use="required" />
    </complexType>
    
    <complexType name="FunctionTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="argument" type="com:ArgumentType" minOccurs="0" maxOccurs="unbounded" />
            <element name="returns"  type="com:ReturnType" minOccurs="0" maxOccurs="1" />
        </sequence>
        
        <attribute name="name"  type="com:IdType" use="required" />
        <attribute name="space" type="string" />
    </complexType>
    
    <complexType name="ArgumentType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="type" type="com:ValueTypeType" use="optional" default="undefined" />
        <attribute name="required" type="boolean" default="false" />
        <attribute name="default" type="anySimpleType" use="optional" />
    </complexType>
    
    <complexType name="ReturnType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="type" type="com:ValueTypeType" use="optional" default="undefined" />
    </complexType>
    
    <complexType name="DocumentationType" mixed="true">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <any namespace="##any" processContents="lax" />
        </sequence>
        
        <attribute name="format" type="com:DocumentationFormatType" use="optional" />
    </complexType>
    
    <simpleType name="ValueTypeType">
        <union memberTypes="com:PrimitiveSimpleTypeType string" />
    </simpleType>
    
    <simpleType name="PrimitiveSimpleTypeType">
        <restriction base="string">
            <enumeration value="undefined" />
            <enumeration value="literal" />
            <enumeration value="string" />
            <enumeration value="number" />
            <enumeration value="boolean" />
            <enumeration value="object" />
            <enumeration value="function" />
            <enumeration value="date" />
            <enumeration value="percentage" />
        </restriction>
    </simpleType>
    
    <simpleType name="ComplexUseType">
        <restriction base="string">
            <enumeration value="literal" />
            <enumeration value="expanded" />
            <enumeration value="any" />
        </restriction>
    </simpleType>
    
    <simpleType name="PropertyExpandUseType">
        <restriction base="string">
            <enumeration value="optional" />
            <enumeration value="required" />
        </restriction>
    </simpleType>
    
    <!-- A measure of difficulty or frequency of use of a property -->
    <simpleType name="PropertyLevelType">
        <restriction base="string">
            <enumeration value="basic" />
            <enumeration value="intermediate" />
            <enumeration value="advanced" />
        </restriction>
    </simpleType>
    
    <simpleType name="IdType">
        <restriction base="NMTOKEN" />
    </simpleType>
    
    <simpleType name="IdTypeList">
        <list itemType="com:IdType" />
    </simpleType>
    
    <simpleType name="DocumentationFormatType">
        <restriction base="string">
           <enumeration value="markdown" />
           <enumeration value="jsdoc" />
           <enumeration value="com" />
        </restriction>
    </simpleType>
</schema>

=== tahopen/ccc/doc/model/varia/atoms/markAnchor.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:atomType name="MarkAnchor" space="pvc.options.varia" base="string">
        <c:documentation>
            The anchors that are available to all protovis marks,
            with the exception of the Wedge mark 
            (see <c:link to="pvc.options.varia.WedgeAnchor" />).
        </c:documentation>
        
        <c:atom name="Top"    value="'top'" />
        <c:atom name="Left"   value="'left'" />
        <c:atom name="Center" value="'center'" />
        <c:atom name="Bottom" value="'bottom'" />
        <c:atom name="Right"  value="'right'" />
    </c:atomType>
</c:model>

=== tahopen/ccc/doc/model/varia/tooltip.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model
        xmlns:c="urn:webdetails/com/2012"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
        xmlns="http://www.w3.org/1999/xhtml">

    <c:complexType name="Tooltip" space="pvc.options" use="any">
        <c:documentation>
            The options documentation class of the tooltip.
        </c:documentation>

        <c:property name="enabled" type="boolean" default="true">
            <c:documentation>
                Indicates if the tooltip is enabled.
            </c:documentation>
        </c:property>
        
        <c:property name="className" type="string" default="''">
            <c:documentation>
                A custom class to mark the root tooltip element.
                
                The root tooltip element is always marked with the class <tt>tipsy</tt>.
                This option allows you to specify an additional class to style the tooltip
                differently for a single chart or group of charts.
            </c:documentation>
        </c:property>
        
        <c:property name="gravity" type="pvc.options.varia.TooltipGravity">
            <c:documentation>
                The preferred tooltip gravity.

                The default value depends on the chart type.
                Most use the <c:link to="pvc.options.varia.TooltipGravity#South"/> gravity,
                but others, like the Pie chart,
                calculate an adequate gravity per visual element.

                When using the preferred gravity causes the
                tooltip to be placed off the browser window,
                a more suitable gravity may be automatically chosen.
            </c:documentation>
        </c:property>

        <c:property name="animate" type="number" excludeIn="cde">
            <c:documentation>
                The duration for the tooltip move animation, in milliseconds.

                A value of <tt>0</tt> disables the move animation.

                The default value depends on
                the value of <c:link to="pvc.options.Tooltip#followMouse" />.
                When <tt>false</tt>, the default value is <tt>400</tt> ms.
                Otherwise, it is <tt>0</tt>, resulting in no animation.
            </c:documentation>
        </c:property>

        <c:property name="delayIn" type="number" default="200" excludeIn="cde">
            <c:documentation>
                The delay for the tooltip to show, in milliseconds.
            </c:documentation>
        </c:property>

        <c:property name="delayOut" type="number" default="80" excludeIn="cde">
            <c:documentation>
                The delay for the tooltip to hide, in milliseconds.
            </c:documentation>
        </c:property>

        <c:property name="offset" type="number">
            <c:documentation>
                The distance of the closest tooltip edge or corner
                to the visual element's tooltip anchor point, in pixel units.

                The default value depends on the chart type.
            </c:documentation>
        </c:property>

        <c:property name="opacity" type="number" default="0.9">
            <c:documentation>
                The opacity level of the tooltip box (range from 0, completely transparent, to 1).
            </c:documentation>
        </c:property>

        <c:property name="html" type="boolean" default="true">
            <c:documentation>
                Indicates if the tooltip text
                that the format function builds
                is in HTML format.
            </c:documentation>
        </c:property>

        <c:property name="format" type="pvc.options.varia.TooltipFormatter">
            <c:documentation>
                A callback function that is called
                to build the tooltip of a visual element.

                If <c:link to="#html" /> is <tt>true</tt>,
                the resulting text must be valid HTML,
                otherwise,
                it is considered plain text.
            </c:documentation>
        </c:property>

        <c:property name="useCorners" type="boolean">
            <c:documentation>
                Indicates if the collateral tooltip gravities should be
                aligned with corners.

                Most chart types use a default value of <tt>false</tt>.
            </c:documentation>
        </c:property>

        <c:property name="arrowVisible" type="boolean">
            <c:documentation>
                Indicates if the tooltip shows an arrow
                pointing to the
                visual element's anchor point.

                Most chart types use a default value of <tt>true</tt>.
            </c:documentation>
        </c:property>

        <c:property name="followMouse" type="boolean" default="false">
            <c:documentation>
                Indicates if the
                visual element's anchor point
                should be the current mouse position.
            </c:documentation>
        </c:property>

        <c:property name="fade" type="boolean" default="true">
            <c:documentation>
                Indicates if the tooltip fades in and out,
                after the corresponding delay has expired.
            </c:documentation>
        </c:property>
    </c:complexType>

</c:model>

=== tahopen/ccc/doc/model/varia/functions/userSelectionAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:functionType name="UserSelectionAction" space="pvc.options.varia">
        <c:documentation>
            A callback function that is called
            when the user performs a selection,
            but before the corresponding datums' selected state is actually changed.
        </c:documentation>
        <c:argument name="this" type="pvc.visual.Context" required="true">
            <c:documentation>
                The CCC visual context object.
            </c:documentation>
        </c:argument>
        <c:argument name="selectingDatums" type="list(pvc.data.Datum)" required="true">
            <c:documentation>
                An array with the datums that will be selected by the current operation.
            </c:documentation>
        </c:argument>
        <c:argument name="selectingGroup" type="pvc.data.Data">
            <c:documentation>
                A data group, if the current operation will only select a single group, otherwise no
                value.
            </c:documentation>
        </c:argument>
        <c:returns type="list(pvc.data.Datum)">
            <c:documentation>
                The datums that should be actually selected.
            </c:documentation>
        </c:returns>
    </c:functionType>
</c:model>

=== tahopen/ccc/doc/model/pvc.options.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <!-- NAMESPACES -->
    <c:space name="pvc">
        <c:documentation>
            The global CCC namespace. 
        </c:documentation>
    </c:space>
    
    <c:space name="pvc.options">
        <c:documentation>
            The CCC options namespace.
            
            All types of this namespace,
            as well as of the namespaces below this one, 
            are <b>documentation</b> types -
            they do not exist, in code, 
            and serve only to document the structure of the options objects 
            that each chart type accepts in its constructor.
            
            <c:example>
                The following code shows how to 
                create and configure a very simple CCC Bar chart:
            <pre>// Options are placed in a plain JS object
var options = {
    title:  "A CCC Bar chart",
    legend: true,
    crosstabMode: false
};

var data = {
    metadata: [
        {colIndex: 0, colType: "String", colName: "Series"}, 
        {colIndex: 1, colType: "String", colName: "Category"}, 
        {colIndex: 2, colType: "String", colName: "Value"}
    ],
    resultset: [
        ["London", "2010-01-02", 1],
        ["London", "2010-01-03", 2],
        ["London", "2010-01-04", 3],
        ["London", "2010-01-05", 2],
        ["Paris",  "2010-01-01", 3],
        ["Paris",  "2010-01-02", 6],
        ["Paris",  "2010-01-04", 1],
        ["Paris",  "2010-01-05", 7],
        ["Lisbon", "2010-01-01", 3],
        ["Lisbon", "2010-01-02", 2],
        ["Lisbon", "2010-01-03", 1],
        ["Lisbon", "2010-01-04", 5]
    ]
};

new pvc.BarChart(options)
.setData(data)
.render();</pre>
            Note that the options object is a plain JavaScript object,
            and not a <c:link to="pvc.options.charts.BarChart" />
            </c:example>
        </c:documentation>
    </c:space>
    
    <c:space name="pvc.options.ext">
        <c:documentation>
            The namespace of CCC chart extension point classes. 
        </c:documentation>
    </c:space>
    
    
    <c:include the="charts/_charts.xml" />
    <c:include the="marks/_marks.xml" />
    <c:include the="axes/_axes.xml" />
    <c:include the="panels/_panels.xml" />
    <c:include the="plots/_plots.xml" />
    <c:include the="facets/_facets.xml" />
    <c:include the="format/_format.xml" />
    <c:include the="data/_data.xml" />
    <c:include the="varia/_varia.xml" />
     
</c:model>

=== tahopen/ccc/doc/model/facets/chartTrend.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:facetType name="CategoricalChartTrendFacet" space="pvc.options.charts">
        <c:documentation>
            The options documentation class of the categorical trend facet.
        </c:documentation>
        
        <c:property name="trend" type="pvc.options.plots.TrendPointPlot" category="Plots">
            <c:documentation>
                The trend plot is activated when 
                the <i>other</i> chart plots indicate that their 
                data should be trended.
                
                To activate trending for a plot specify 
                its <tt>trend type</tt> option.
            </c:documentation>
        </c:property>
        
    </c:facetType>
    
    <c:facetType name="MetricChartTrendFacet" space="pvc.options.charts">
        <c:documentation>
            The options documentation class of the metric trend facet.
        </c:documentation>
        
        <c:property name="trend" type="pvc.options.plots.TrendMetricPointPlot" category="Plots">
            <c:documentation>
                The trend plot is activated when 
                the <i>other</i> chart plots indicate that their 
                data should be trended.
                
                To activate trending for a plot specify 
                its <tt>trend type</tt> option.
            </c:documentation>
        </c:property>
        
    </c:facetType>
    
    <c:complexType name="TrendPointPlot" 
                   space="pvc.options.plots"
                   base="pvc.options.plots.PointPlot"
                   use="expanded">
        <c:documentation>
            The options documentation class of the <b>point</b> plot 
            used for trends of categorical charts.
        </c:documentation>
        
        <c:property name="trend" type="pvc.options.varia.PlotTrending" fixed="null" category="Data">
            <c:documentation>
                Trends are not supported by this plot type.
            </c:documentation>
        </c:property>
        
        <c:property name="nullInterpolationMode" type="pvc.options.varia.NullInterpolationMode" category="Data" fixed="null">
            <c:documentation>
                The null interpolation mode is not supported by this plot type.
            </c:documentation>
        </c:property>
        
         <c:property name="linesVisible" type="boolean" default="true" category="Style">
            <c:documentation>
                Indicates if the visual elements are connected
                with lines.
            </c:documentation>
        </c:property>
        
        <c:property name="colorAxis" type="number" category="Axes" default="2">
            <c:documentation>
                The index of the color axis to use for the plot.
            </c:documentation>
        </c:property>
    </c:complexType>
    
    <c:complexType name="TrendMetricPointPlot" 
                   space="pvc.options.plots"
                   base="pvc.options.plots.MetricPointPlot"
                   use="expanded">
        <c:documentation>
            The options documentation class of the <b>metric point</b> plot 
            used for trends of scatter charts.
        </c:documentation>
        
        <c:property name="trend" type="pvc.options.varia.PlotTrending" fixed="null" category="Data">
            <c:documentation>
                Trends are not supported by this plot type.
            </c:documentation>
        </c:property>
        
        <c:property name="nullInterpolationMode" type="pvc.options.varia.NullInterpolationMode" category="Data" fixed="null">
            <c:documentation>
                The null interpolation mode is not supported by this plot type.
            </c:documentation>
        </c:property>
        
         <c:property name="linesVisible" type="boolean" default="true" category="Style">
            <c:documentation>
                Indicates if the visual elements are connected
                with lines.
            </c:documentation>
        </c:property>
        
        <c:property name="colorAxis" type="number" category="Axes" default="2">
            <c:documentation>
                The index of the color axis to use for the plot.
            </c:documentation>
        </c:property>
        
        <c:property name="orthoAxis" fixed="1" type="number" category="Axes">
            <c:documentation>
                The index of the orthogonal cartesian axis to use for the plot.
            </c:documentation>
        </c:property>
        
        <!--  TODO: confirm this assumption -->
        <c:property name="nullShape" fixed="null" type="pvc.options.varia.DotShapeType" category="Style">
            <c:documentation>
                The trend does not contain null size values.
            </c:documentation>
        </c:property>
        
    </c:complexType>
</c:model>

=== tahopen/ccc/doc/model/axes/_axes.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:space name="pvc.options.axes">
        <c:documentation>
            The namespace of CCC axes options classes. 
        </c:documentation>
    </c:space>
    
    <c:include the="axes/axis-color.xml" />
    <c:include the="axes/axis-size.xml"  />
    
    <c:include the="axes/axis-cartesian.xml" />
    <c:include the="axes/axis-cartesian-discrete.xml" />
    <c:include the="axes/axis-cartesian-continuous.xml" />
    <c:include the="axes/axis-cartesian-numeric.xml" />
</c:model>
